// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoloCoachApi.DataBase;

#nullable disable

namespace SoloCoachApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260319104131_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoloCoachApi.Models.Exercise", b =>
                {
                    b.Property<int>("IdExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_exercise");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExercise"));

                    b.Property<string>("Complexity")
                        .HasColumnType("text")
                        .HasColumnName("complexity");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("picture_url");

                    b.HasKey("IdExercise");

                    b.ToTable("exercise");
                });

            modelBuilder.Entity("SoloCoachApi.Models.ExerciseGroupsMuscle", b =>
                {
                    b.Property<int>("IdExerciseGroupsMuscle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_exercise_groups_muscle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExerciseGroupsMuscle"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<int>("GroupsMusclesId")
                        .HasColumnType("integer")
                        .HasColumnName("groups_muscles_id");

                    b.HasKey("IdExerciseGroupsMuscle");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("GroupsMusclesId");

                    b.ToTable("exercise_groups_muscles");
                });

            modelBuilder.Entity("SoloCoachApi.Models.Goal", b =>
                {
                    b.Property<int>("IdGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_goal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGoal"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<float>("TargetWeight")
                        .HasColumnType("real")
                        .HasColumnName("target_weight");

                    b.Property<string>("TypeGoal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_goal");

                    b.HasKey("IdGoal");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("SoloCoachApi.Models.GroupsMuscle", b =>
                {
                    b.Property<int>("IdGroupsMuscle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_groups_muscle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGroupsMuscle"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("IdGroupsMuscle");

                    b.ToTable("groups_muscles");
                });

            modelBuilder.Entity("SoloCoachApi.Models.MetricsUser", b =>
                {
                    b.Property<int>("IdMetricsUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_metrics_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMetricsUser"));

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("text")
                        .HasColumnName("activity_level");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("ExperienceLevel")
                        .HasColumnType("text")
                        .HasColumnName("experience_level");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("height");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("IdMetricsUser");

                    b.HasIndex("GoalId");

                    b.ToTable("metrics_users");
                });

            modelBuilder.Entity("SoloCoachApi.Models.PlanWorkout", b =>
                {
                    b.Property<int>("IdPlanWorkout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_plan_workouts");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanWorkout"));

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_id");

                    b.HasKey("IdPlanWorkout");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("plan_workouts");
                });

            modelBuilder.Entity("SoloCoachApi.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRole"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("IdRole");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SoloCoachApi.Models.TrainingExercise", b =>
                {
                    b.Property<int>("IdTrainingExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_training_exercise");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrainingExercise"));

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("execution_order");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<int>("RestTime")
                        .HasColumnType("integer")
                        .HasColumnName("rest_time");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_id");

                    b.HasKey("IdTrainingExercise");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("training_exercises");
                });

            modelBuilder.Entity("SoloCoachApi.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<int?>("MetricsUserId")
                        .HasColumnType("integer")
                        .HasColumnName("metrics_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("IdUser");

                    b.HasIndex("MetricsUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SoloCoachApi.Models.Workout", b =>
                {
                    b.Property<int>("IdWorkout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_workout");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWorkout"));

                    b.Property<string>("Complexity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complexity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TypeWorkout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_workout");

                    b.HasKey("IdWorkout");

                    b.ToTable("workouts");
                });

            modelBuilder.Entity("SoloCoachApi.Models.WorkoutCalendar", b =>
                {
                    b.Property<int>("IdWorkoutCalendar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_workout_calendar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWorkoutCalendar"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_id");

                    b.HasKey("IdWorkoutCalendar");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_calendars");
                });

            modelBuilder.Entity("SoloCoachApi.Models.WorkoutUser", b =>
                {
                    b.Property<int>("IdWorkoutUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_workout_users");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWorkoutUser"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_id");

                    b.HasKey("IdWorkoutUser");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_users");
                });

            modelBuilder.Entity("SoloCoachApi.Models.WorkoutUserLog", b =>
                {
                    b.Property<int>("IdWorkoutUserLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_workout_user_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWorkoutUserLog"));

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer")
                        .HasColumnName("repetitions");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_id");

                    b.Property<int>("WorkoutUserId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_user_id");

                    b.HasKey("IdWorkoutUserLog");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("WorkoutUserId");

                    b.ToTable("workout_user_logs");
                });

            modelBuilder.Entity("SoloCoachApi.Models.ExerciseGroupsMuscle", b =>
                {
                    b.HasOne("SoloCoachApi.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloCoachApi.Models.GroupsMuscle", "GroupsMuscle")
                        .WithMany()
                        .HasForeignKey("GroupsMusclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("GroupsMuscle");
                });

            modelBuilder.Entity("SoloCoachApi.Models.MetricsUser", b =>
                {
                    b.HasOne("SoloCoachApi.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("SoloCoachApi.Models.PlanWorkout", b =>
                {
                    b.HasOne("SoloCoachApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloCoachApi.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SoloCoachApi.Models.TrainingExercise", b =>
                {
                    b.HasOne("SoloCoachApi.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloCoachApi.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SoloCoachApi.Models.User", b =>
                {
                    b.HasOne("SoloCoachApi.Models.MetricsUser", "MetricsUser")
                        .WithMany()
                        .HasForeignKey("MetricsUserId");

                    b.HasOne("SoloCoachApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetricsUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SoloCoachApi.Models.WorkoutCalendar", b =>
                {
                    b.HasOne("SoloCoachApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloCoachApi.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SoloCoachApi.Models.WorkoutUser", b =>
                {
                    b.HasOne("SoloCoachApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloCoachApi.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("SoloCoachApi.Models.WorkoutUserLog", b =>
                {
                    b.HasOne("SoloCoachApi.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoloCoachApi.Models.WorkoutUser", "WorkoutUser")
                        .WithMany()
                        .HasForeignKey("WorkoutUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");

                    b.Navigation("WorkoutUser");
                });
#pragma warning restore 612, 618
        }
    }
}
