services:
  db:
    image: postgres:16
    container_name: solocoach_db
    restart: always
    environment:
      POSTGRES_DB: SoloCoach
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
    # ports больше не нужны снаружи, но можно оставить для дебага
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./SoloCoachApi
      dockerfile: Dockerfile
    container_name: solocoach_api
    restart: always
    # порт 8081 больше не нужно открывать наружу
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=SoloCoach;Username=postgres;Password=1;Port=5432
      - Smtp__Host=smtp.gmail.com
      - Smtp__Port=587
      - Smtp__User=solocoachsport@gmail.com
      - Smtp__Password=jddp wtwe kmsu mhzl
    depends_on:
      - db

  site:
    build:
      context: ./solocoachsite
      dockerfile: Dockerfile
    container_name: solocoach_site
    restart: always
    # порт 3000 больше не нужно открывать наружу
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: solocoach_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - site
      - api

volumes:
  postgres_data: